[2025-02-16T22:11:48.807+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-02-16T22:11:30.822967+00:00 [queued]>
[2025-02-16T22:11:48.848+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-02-16T22:11:30.822967+00:00 [queued]>
[2025-02-16T22:11:48.849+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-16T22:11:48.907+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): kafka_data_stream> on 2025-02-16 22:11:30.822967+00:00
[2025-02-16T22:11:48.926+0000] {standard_task_runner.py:57} INFO - Started process 976 to run task
[2025-02-16T22:11:48.944+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'kafka_data_stream', 'manual__2025-02-16T22:11:30.822967+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmpwco91yzp']
[2025-02-16T22:11:48.947+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask kafka_data_stream
[2025-02-16T22:11:49.130+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.kafka_data_stream manual__2025-02-16T22:11:30.822967+00:00 [running]> on host de5e2408bcb1
[2025-02-16T22:11:49.426+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='kafka_data_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T22:11:30.822967+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T22:11:30.822967+00:00'
[2025-02-16T22:12:00.922+0000] {logging_mixin.py:154} INFO - Dataset downloaded successfully.
[2025-02-16T22:12:01.246+0000] {logging_mixin.py:154} INFO - Dataset extracted successfully.
[2025-02-16T22:12:01.254+0000] {logging_mixin.py:154} INFO - No CSV file found in extracted data.
[2025-02-16T22:12:01.262+0000] {logging_mixin.py:154} INFO - Dataset preparation failed.
[2025-02-16T22:12:01.268+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-16T22:12:01.343+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=kafka_spark_dag, task_id=kafka_data_stream, execution_date=20250216T221130, start_date=20250216T221148, end_date=20250216T221201
[2025-02-16T22:12:01.465+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-16T22:12:01.609+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
