[2025-02-16T21:59:37.902+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T21:57:43.190949+00:00 [queued]>
[2025-02-16T21:59:37.925+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T21:57:43.190949+00:00 [queued]>
[2025-02-16T21:59:37.926+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-16T21:59:37.972+0000] {taskinstance.py:1382} INFO - Executing <Task(DockerOperator): pyspark_consumer> on 2025-02-16 21:57:43.190949+00:00
[2025-02-16T21:59:38.014+0000] {standard_task_runner.py:57} INFO - Started process 5494 to run task
[2025-02-16T21:59:38.046+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'kafka_spark_dag', 'pyspark_consumer', 'manual__2025-02-16T21:57:43.190949+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dag_kafka_spark.py', '--cfg-path', '/tmp/tmprm8u8036']
[2025-02-16T21:59:38.054+0000] {standard_task_runner.py:85} INFO - Job 29: Subtask pyspark_consumer
[2025-02-16T21:59:38.424+0000] {task_command.py:416} INFO - Running <TaskInstance: kafka_spark_dag.pyspark_consumer manual__2025-02-16T21:57:43.190949+00:00 [running]> on host de5e2408bcb1
[2025-02-16T21:59:38.888+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='kafka_spark_dag' AIRFLOW_CTX_TASK_ID='pyspark_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-16T21:57:43.190949+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-16T21:57:43.190949+00:00'
[2025-02-16T21:59:39.006+0000] {docker.py:343} INFO - Starting docker container from image rappel-conso/spark:latest
[2025-02-16T21:59:39.017+0000] {docker.py:351} WARNING - Using remote engine or docker-in-docker and mounting temporary volume from host is not supported. Falling back to `mount_tmp_dir=False` mode. You can set `mount_tmp_dir` parameter to False to disable mounting and remove the warning
[2025-02-16T21:59:40.927+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:59:40.91 [0m[38;5;2mINFO [0m ==>
[2025-02-16T21:59:40.954+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:59:40.93 [0m[38;5;2mINFO [0m ==> [1mWelcome to the Bitnami spark container[0m
[2025-02-16T21:59:40.961+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:59:40.95 [0m[38;5;2mINFO [0m ==> Subscribe to project updates by watching [1mhttps://github.com/bitnami/containers[0m
[2025-02-16T21:59:40.966+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:59:40.96 [0m[38;5;2mINFO [0m ==> Did you know there are enterprise versions of the Bitnami catalog? For enhanced secure software supply chain features, unlimited pulls from Docker, LTS support, or application customization, see Bitnami Premium or Tanzu Application Catalog. See https://www.arrow.com/globalecs/na/vendors/bitnami/ for more information.
[2025-02-16T21:59:40.970+0000] {docker.py:413} INFO - [38;5;6mspark [38;5;5m21:59:40.96 [0m[38;5;2mINFO [0m ==>
[2025-02-16T21:59:41.024+0000] {docker.py:413} INFO - 
[2025-02-16T21:59:56.855+0000] {docker.py:413} INFO - :: loading settings :: url = jar:file:/opt/bitnami/spark/jars/ivy-2.5.1.jar!/org/apache/ivy/core/settings/ivysettings.xml
[2025-02-16T21:59:57.076+0000] {docker.py:413} INFO - Ivy Default Cache set to: /opt/bitnami/spark/.ivy2/cache
The jars for the packages stored in: /opt/bitnami/spark/.ivy2/jars
[2025-02-16T21:59:57.103+0000] {docker.py:413} INFO - org.postgresql#postgresql added as a dependency
[2025-02-16T21:59:57.105+0000] {docker.py:413} INFO - org.apache.spark#spark-sql-kafka-0-10_2.12 added as a dependency
[2025-02-16T21:59:57.106+0000] {docker.py:413} INFO - :: resolving dependencies :: org.apache.spark#spark-submit-parent-200b9de6-5e75-42e4-ab9e-41e31aa818c7;1.0
	confs: [default]
[2025-02-16T21:59:59.606+0000] {docker.py:413} INFO - found org.postgresql#postgresql;42.5.4 in central
[2025-02-16T22:00:00.426+0000] {docker.py:413} INFO - found org.checkerframework#checker-qual;3.5.0 in central
[2025-02-16T22:00:04.730+0000] {docker.py:413} INFO - found org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T22:00:06.044+0000] {docker.py:413} INFO - found org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 in central
[2025-02-16T22:00:06.278+0000] {docker.py:413} INFO - found org.apache.kafka#kafka-clients;3.4.1 in central
[2025-02-16T22:00:06.528+0000] {docker.py:413} INFO - found org.lz4#lz4-java;1.8.0 in central
[2025-02-16T22:00:06.914+0000] {docker.py:413} INFO - found org.xerial.snappy#snappy-java;1.1.10.3 in central
[2025-02-16T22:00:08.202+0000] {docker.py:413} INFO - found org.slf4j#slf4j-api;2.0.7 in central
[2025-02-16T22:00:10.303+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-runtime;3.3.4 in central
[2025-02-16T22:00:10.878+0000] {docker.py:413} INFO - found org.apache.hadoop#hadoop-client-api;3.3.4 in central
[2025-02-16T22:00:13.058+0000] {docker.py:413} INFO - found commons-logging#commons-logging;1.1.3 in central
[2025-02-16T22:00:13.357+0000] {docker.py:413} INFO - found com.google.code.findbugs#jsr305;3.0.0 in central
[2025-02-16T22:00:15.939+0000] {docker.py:413} INFO - found org.apache.commons#commons-pool2;2.11.1 in central
[2025-02-16T22:00:16.178+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.4/postgresql-42.5.4.jar ...
[2025-02-16T22:00:16.644+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.postgresql#postgresql;42.5.4!postgresql.jar (540ms)
[2025-02-16T22:00:16.702+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.0/spark-sql-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T22:00:16.933+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0!spark-sql-kafka-0-10_2.12.jar (274ms)
[2025-02-16T22:00:17.011+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/checkerframework/checker-qual/3.5.0/checker-qual-3.5.0.jar ...
[2025-02-16T22:00:17.209+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.checkerframework#checker-qual;3.5.0!checker-qual.jar (256ms)
[2025-02-16T22:00:17.281+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.0/spark-token-provider-kafka-0-10_2.12-3.5.0.jar ...
[2025-02-16T22:00:17.385+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0!spark-token-provider-kafka-0-10_2.12.jar (178ms)
[2025-02-16T22:00:17.466+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.4.1/kafka-clients-3.4.1.jar ...
[2025-02-16T22:00:19.016+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.kafka#kafka-clients;3.4.1!kafka-clients.jar (1613ms)
[2025-02-16T22:00:19.089+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.0/jsr305-3.0.0.jar ...
[2025-02-16T22:00:19.157+0000] {docker.py:413} INFO - [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.0!jsr305.jar (125ms)
[2025-02-16T22:00:19.228+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar ...
[2025-02-16T22:00:19.348+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.commons#commons-pool2;2.11.1!commons-pool2.jar (177ms)
[2025-02-16T22:00:19.409+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-runtime/3.3.4/hadoop-client-runtime-3.3.4.jar ...
[2025-02-16T22:00:36.556+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-runtime;3.3.4!hadoop-client-runtime.jar (17204ms)
[2025-02-16T22:00:36.625+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/lz4/lz4-java/1.8.0/lz4-java-1.8.0.jar ...
[2025-02-16T22:00:36.921+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.lz4#lz4-java;1.8.0!lz4-java.jar (350ms)
[2025-02-16T22:00:36.989+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.10.3/snappy-java-1.1.10.3.jar ...
[2025-02-16T22:00:37.771+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.xerial.snappy#snappy-java;1.1.10.3!snappy-java.jar(bundle) (837ms)
[2025-02-16T22:00:37.827+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar ...
[2025-02-16T22:00:37.936+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.slf4j#slf4j-api;2.0.7!slf4j-api.jar (162ms)
[2025-02-16T22:00:37.994+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client-api/3.3.4/hadoop-client-api-3.3.4.jar ...
[2025-02-16T22:00:58.326+0000] {docker.py:413} INFO - [SUCCESSFUL ] org.apache.hadoop#hadoop-client-api;3.3.4!hadoop-client-api.jar (20388ms)
[2025-02-16T22:00:58.395+0000] {docker.py:413} INFO - downloading https://repo1.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar ...
[2025-02-16T22:00:58.487+0000] {docker.py:413} INFO - [SUCCESSFUL ] commons-logging#commons-logging;1.1.3!commons-logging.jar (152ms)
[2025-02-16T22:00:58.495+0000] {docker.py:413} INFO - :: resolution report :: resolve 18988ms :: artifacts dl 42402ms
[2025-02-16T22:00:58.505+0000] {docker.py:413} INFO - :: modules in use:
[2025-02-16T22:00:58.509+0000] {docker.py:413} INFO - com.google.code.findbugs#jsr305;3.0.0 from central in [default]
[2025-02-16T22:00:58.513+0000] {docker.py:413} INFO - commons-logging#commons-logging;1.1.3 from central in [default]
[2025-02-16T22:00:58.515+0000] {docker.py:413} INFO - org.apache.commons#commons-pool2;2.11.1 from central in [default]
[2025-02-16T22:00:58.519+0000] {docker.py:413} INFO - org.apache.hadoop#hadoop-client-api;3.3.4 from central in [default]
	org.apache.hadoop#hadoop-client-runtime;3.3.4 from central in [default]
	org.apache.kafka#kafka-clients;3.4.1 from central in [default]
	org.apache.spark#spark-sql-kafka-0-10_2.12;3.5.0 from central in [default]
	org.apache.spark#spark-token-provider-kafka-0-10_2.12;3.5.0 from central in [default]
	org.checkerframework#checker-qual;3.5.0 from central in [default]
	org.lz4#lz4-java;1.8.0 from central in [default]
	org.postgresql#postgresql;42.5.4 from central in [default]
	org.slf4j#slf4j-api;2.0.7 from central in [default]
[2025-02-16T22:00:58.527+0000] {docker.py:413} INFO - org.xerial.snappy#snappy-java;1.1.10.3 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
[2025-02-16T22:00:58.537+0000] {docker.py:413} INFO - |      default     |   13  |   13  |   13  |   0   ||   13  |   13  |
[2025-02-16T22:00:58.544+0000] {docker.py:413} INFO - ---------------------------------------------------------------------
[2025-02-16T22:00:58.632+0000] {docker.py:413} INFO - :: retrieving :: org.apache.spark#spark-submit-parent-200b9de6-5e75-42e4-ab9e-41e31aa818c7
[2025-02-16T22:00:58.634+0000] {docker.py:413} INFO - confs: [default]
[2025-02-16T22:00:59.354+0000] {docker.py:413} INFO - 13 artifacts copied, 0 already retrieved (58001kB/704ms)
[2025-02-16T22:01:01.583+0000] {docker.py:413} INFO - 25/02/16 22:01:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-02-16T22:01:04.896+0000] {docker.py:413} INFO - python3: can't open file '/opt/bitnami/spark/scripts/spark_pgsql.py': [Errno 2] No such file or directory
[2025-02-16T22:01:04.950+0000] {docker.py:413} INFO - 25/02/16 22:01:04 INFO ShutdownHookManager: Shutdown hook called
[2025-02-16T22:01:04.953+0000] {docker.py:413} INFO - 25/02/16 22:01:04 INFO ShutdownHookManager: Deleting directory /tmp/spark-c23d863c-92b1-4b9e-87df-eb67d07e7a01
[2025-02-16T22:01:05.749+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://docker-proxy:2375/v1.47/containers/create

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 348, in _run_image
    return self._run_image_with_mounts([*self.mounts, tmp_mount], add_tmp_variable=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 375, in _run_image_with_mounts
    self.container = self.cli.create_container(
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/airflow/.local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 400 Client Error for http://docker-proxy:2375/v1.47/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/airflowtmpy9ocrd4u")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 486, in execute
    return self._run_image()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 357, in _run_image
    return self._run_image_with_mounts(self.mounts, add_tmp_variable=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/docker/operators/docker.py", line 421, in _run_image_with_mounts
    raise DockerContainerFailedException(f"Docker container failed: {result!r}", logs=log_lines)
airflow.providers.docker.exceptions.DockerContainerFailedException: Docker container failed: {'StatusCode': 2}
[2025-02-16T22:01:05.794+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=kafka_spark_dag, task_id=pyspark_consumer, execution_date=20250216T215743, start_date=20250216T215937, end_date=20250216T220105
[2025-02-16T22:01:05.882+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 29 for task pyspark_consumer (Docker container failed: {'StatusCode': 2}; 5494)
[2025-02-16T22:01:05.973+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-16T22:01:06.054+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
